sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "vV121LUqcnzkdouOQsE2Q69HR/NIfilgXMWvU72f/4P1U5K3mIUJjlNUJg1eVr6D0Dg10xAwBZCUUGPPIIcnge3jJ/O8erUJ6ymrfDtwU5KxhLfTJkglMAcOHGXwAZCKkQ6aKR2Lwpj1Wag+5lGq+XFu1Afd+sdTomtC6LvVz8aLFUhNMURwCgnblwzrK3dw/Anj330MiRtM86CC+sSQLmqSHBlQKls9Xt69ETet9a0G3HwB9ksSwZODSuHFcxusMk9F/JnBZRSIV4o8zDT/HMjhwDTOO4vyWapxd1mlDlsS+vtk/jBgZap0oBLbb/DYx6pgi5YjsZ8DtChQl/SViOVlH6VoXA9XCwbDXXqgCxJnCNJ7WhRjd8yadYy1Acrbf3EX1xTxkKKMgVa1/rFxCTo5PK7/i/nyfsoO7Il3vvRHZqbjmwA0bUMCEediFfVu4avXvL/KLohlnG+NW0XZC8RTGn+DAIFdALCv5kqsNnN4c6nckVTPawRL91RT/kADSMx0AIpuW5yUhA9tphZBk6IvkqMHSU9nSwraoDiaxOXEqzRdfqGv9qnaR1C6BkGtAaU/fgFnGb8Ux4JBArm/9qHDN9MtvNChHqKOhI7Rw4uFs4qPP/nFkMh94Hu09kUaHgbteAetFWmd27o6qD/EP1tg4pNNS5g1NS40EEW7IYE="
  - secure: "JsjZmM6h++I2S3owHUgeEuuhYtgiIhSCoi9xRgKst1wtAG+HJIZqq0FaMS8klpn3VsUnSGQR/3WxlQ+wf/0ShudNiRn60/xetfxG2pNgZFmpr3vp/XZr3HRyA+OH5BcJFpmjcA5YXrCkJ6bJZMtJPGTPz1JdE5c45AVACL6MAP1Tk0ouVt5Mdf4PZaGZGd1utLaLlO64FW8HHZSXho5muEi/bfToENgwWHPl1fHqcWT2blODdt4nyAiHA5zAl3Uj13JkdB70tnMXipMY3S0cy13RAA9+Wqq5j/niLLf6DtvaK3jLLCFDjTL1Qo/H373vb2G5hEjFl/8qDWh05xssAdw6xaF8QgJC9N1Ipwl+ZgaSmf6M2ZAhiVsXQpqV6GPzyiGbR+1TfvZvOrDnujTIDLq4A0UKyGmBAzLF9k0kJ0kNoyGH4xkqVAZWwKyBoIqMr9SuUFt2lDFPyhH94lIOgUY0geG24apal3r9X0V1Yi3HGU1ssa2StSbbmvzDo6ulXw+bxtgYKB82lrhLeRRzbMeEaPNgOayaRrZALfnemDyMr4QSo92vatQAY6p4joCzS9ivsiD2ZvxTgIfajSyn+PzxBHfJAeeMdESed/q0mHM/+1NY4bJSijdLLVFD9GdDmadmlzpEPQ5ClbCsNrJ4xSVX0re57uoiYo8vXoxDghw="
  - secure: "gLAjLwuWNA/WAQru008TB84E/LO2bkw9D/iiyrj5Cp9j9EbAnkNTtyFgu86/Pn/mbCWoaob6T0OxqFU6OOKYifuR2xzzCTAB3w7T7URouRUgCU9fgxkXhoSgykviMSlxfWTHzSOndq4c1Jhy3LPl1eHok9IHeEVWklnSUuuhtQy2nQkA4wl5Ppqxn78YxhjH2SlnAdTOK3stqhIYCKZ4M+90ocKTg8KkKSQpQluorhTC6TbUuYAgSeH2cDAnVfZyv05puIG2ao84ZmQdHPs7tCNO5REJ3caKit+xcPt5rq0Z8rh5uFlkh64Anik8qMvIwWiwAaDtI9KMbZ1QTLMqIImoXz5vYm/SXesr1I91dFLSs9yrctDSbzog9QzYVD8VVcpkxMEBB5Q1gQbHnwUvFtB7yXCdHT22Ykg4t3KAvpVZ6ZfHUqEyk/Ymwt5AXyeRTPW7lyxDAWZ9SkcaRICP4KPMXt5TItf1GB9I68HUOSBDD7NfOcuCcEiEMFxgNZKRo7HIkrKIcZb70/TXEIUtCMLCJ4MXm9DCAFp+ZVkgE+VKiSbWC6b+QblTqPQwhiNtYEzdWhNHnmoR20m16kI1whqUCA+nlyRkV/YlpFu1cqGSQxeY0FI+975bZjA2mBTj8gpXaJySct6q/UoCWFeucHoWOb437jUsTghtXsZNCjI="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
